### ISSUE TITLE
订单查询接口package中的&的转义问题

### ISSUE THREAD

**Issue by akirapanda** [RaymondChou/Rwepay#1]
Raymond你好，感谢提供了ruby下的weixin pay 的sdk。在我的使用中遇到几个问题，请问是否可以和您讨论一下。
微信接口中定义,请求中的字符串无需做额外的转义工作。
我的环境为rails 4.0,默认编码为utf-8.因为订单查询接口中包含&字符，在to_json后会被默认转义成\u0026再在发送至weixin平台，而从将会导致weixin端校验不通过。
解决办法重置to_json在utf8的这步操作，不知道其他用户是否有同样的问题，是否需要提交PR解决。
谢谢！

**Comment by RaymondChou** [comment]
这个好像遇到过 明天我来看下哦

**Comment by RaymondChou** [comment]
试试 0.0.2 这个版本的
